import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  const { data: sessionData, status: sessionStatus } = useSession();
  if (sessionStatus === "loading") {
    return <p>Loading...</p>;
  }
  if (sessionStatus === "unauthenticated") {
    return (<div className="flex grow flex-col items-center text-center uppercase font-bold justify-center gap-4 text-xl">
      <h2 className="text-amber-300">You need to sign in<br/>and be part of 42 Florence to view this page</h2>

      <button
        className="rounded-full cursor-pointer bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn("42-school")}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>)
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col grow">

        <AuthShowcase/>
      </div>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
