import Head from "next/head";
import Link from "next/link";
import { PeerTableView } from "~/components/peers/TableView";

import { api } from "~/utils/api";

export default function Home() {

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header className="flex flex-col justify-center w-full shrink-0 bg-black/20">
				<div className="flex items-center justify-center w-full h-16 shrink-0 bg-black/50">
					<form id="search-form" className="relative flex items-center justify-center w-full h-full">
						<label htmlFor="search" className="sr-only">
							<h2>Nickname dell&apos;intra</h2>
						</label>
						<input type="text" id="search" placeholder="Enter intra's nickname" autoComplete="off"
							className="w-full h-full px-3 py-1 text-base text-center text-white bg-transparent outline-none sm:text-xl font-futura-light" autoFocus />
						<button role="search" type="submit" className="absolute top-0 right-0 p-5 pointer-events-none">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960" className="w-6 h-6 fill-white">
								<path
									d="M784-120 532-372q-30 24-69 38t-83 14q-109 0-184.5-75.5T120-580q0-109 75.5-184.5T380-840q109 0 184.5 75.5T640-580q0 44-14 83t-38 69l252 252-56 56ZM380-400q75 0 127.5-52.5T560-580q0-75-52.5-127.5T380-760q-75 0-127.5 52.5T200-580q0 75 52.5 127.5T380-400Z" />
							</svg>
						</button>
					</form>
				</div>

				<nav className="grid h-16 grid-flow-row grid-cols-2 text-base text-center border-b sm:text-xl border-white/10 flex-nowrap">
					<a data-selectedtab="table" href="#table" className="flex items-center justify-center w-full px-4 py-3 font-mono uppercase border-r hover:text-yellow-200 border-white/10">
						<h2>Table</h2>
					</a>
					<a data-selectedtab="clusters" href="#clusters" className="flex items-center justify-center w-full px-4 py-3 font-mono uppercase hover:text-yellow-200">Clusters map</a>
				</nav>
			</header>

			<dialog id="msg" className="fixed top-0 left-0 z-50 flex-col items-center hidden w-full h-full p-4 font-mono text-white bg-neutral-950/60">
				<header className="flex justify-end w-full h-14">
					<button data-dialog-btn="close" className="h-full text-4xl font-bold text-red-700 hover:text-red-500" >
						&times;
					</button>
				</header>
				<div data-dialog-content className="flex items-center justify-center h-full text-4xl text-center font-futura-bold"></div>
				<footer className="flex justify-center w-full h-14">
					<button onClick={() => window?.location?.reload()} className="flex justify-center p-2 text-2xl border rounded-md hover:bg-slate-950">REFRESH PAGE</button>
				</footer>
			</dialog>
			<main id="main"
				className="relative flex flex-col items-center justify-start w-full overflow-x-hidden overflow-y-hidden xl:items-start xl:justify-center xl:overflow-y-auto xl:w-auto xl:flex-row grow">

				<aside className="sticky top-0 left-0 hidden w-40 h-full px-4 py-3 shrink-0 xl:flex">
					<div data-refetch-cnt className="hidden text-sm font-futura-medium xs:text-sm sm:text-base">Refresh in&nbsp;<span data-refetch-time>0</span>s</div>
				</aside>

				<section id="tab-table" className="relative w-full px-4 pb-1 mx-auto text-xl sm:pb-3">
					<PeerTableView />
				</section>

				<section style={{ display: "none", scrollbarGutter: "stable", }} id="tab-clusters"
					className="flex flex-col items-baseline w-full gap-3 py-1 text-center md:text-center text-xxxs sm:py-2 sm:w-full xs-sm:text-xxs lg:text-sm xl:text-base grow xl:items-center ml-1.5">
				</section>

				<span className="grow shrink-1 xl:hidden"></span>
				<footer
					className="flex items-center justify-between w-full h-10 px-4 py-1 border-t xl:overflow-hidden xl:justify-center xl:flex-col xl:items-center xl:sticky xl:top-0 xl:right-0 xl:grow xl:w-40 xl:h-full xl:py-2 xl:border-none xl:px-0 shrink-0 border-neutral-700/40">
					<h3 data-refetch-cnt className="flex items-center font-futura-light text-sm font-semibold xl:!hidden xs:text-sm sm:text-base whitespace-nowrap">Refresh in&nbsp;<span
						data-refetch-time>0</span>s
					</h3>
					<span className="hidden xl:block grow"></span>
					<span className="overflow-hidden text-transparent select-none text-ellipsis">https://github.com/sandoramix/42-findmypeer</span>
					<a className="block font-mono text-sm text-center xl:w-full whitespace-nowrap xl:bg-black/10 xl:rounded xl:px-3 xl:py-1" href="https://profile.intra.42.fr/users/odudniak" target="_blank" referrerPolicy="no-referrer">Made by @odudniak</a>
				</footer>
			</main>
		</>
	);
}
